### ISSUE TITLE
ParseError: 'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by shaibansid** [alessioalex/angular2-browserify#1]
hi @alessioalex ,
i'm using your workflow for build (angular2 beta1), all is working fine but got stuck in following error

F:\nodeApp\angular2-browserify\node_modules\angular2moment\TimeAgoPipe.ts:3
import {Pipe, ChangeDetectorRef, PipeTransform, OnDestroy} from 'angular2/core';
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'

please help as soon as possible.

**Comment by alessioalex** [comment]
Hi @shaibansid . Delete `node_modules`, reinstall everything again and also install the latest `typescript` available globally: `npm i typescript -g`. Let me know if that fixes the problem.

**Comment by shaibansid** [comment]
@alessioalex Many thanks, by upgrading solve my problem.
